version: 0.1
log:
  level: info
  accesslog:
    disabled: true
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /root/platform/mirror
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
