[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool]
[tool.poetry]
package-mode = false
[tool.poetry.dependencies]
beautifulsoup4 = "*"
kubernetes = ">=4.7.1"
packaging = "*"
pulumi = ">=3"
pulumi_kubernetes = ">=4.11.0"
python = "^3.9"
pyyaml = "*"
