version: "3"

dotenv:
- .env

vars:
  deployment: ci
  project: kargo
  organization: "{{.GITHUB_USER | default `containercraft`}}"
  #pwd: "{{.CODESPACE_VSCODE_FOLDER | default `/workspaces/Kargo`}}"
  pulumi_dir: "{{.PWD}}/.pulumi"
  kube_dir: "{{.PWD}}/.kube"
  kube_config_file: "{{.kube_dir}}/config"
  pulumi_stack_identifier: "{{.organization}}/{{.project}}/{{.deployment}}"
  talos_dir: "{{.PWD}}/.talos"
  talos_patch: "{{.talos_dir}}/patch/cluster.yaml"
  talos_config_file: "{{.talos_dir}}/manifest/talosconfig"
  cluster_name: "talos-kargo-docker"
  exposed_ports: "30590:30590/tcp"
  memory: "8192"
  arch:
    sh: |
      arch=$(uname -m)
      if [ "$arch" = "x86_64" ]; then
        echo "amd64"
      elif [ "$arch" = "aarch64" ] || [ "$arch" = "arm64" ]; then
        echo "arm64"
      else
        echo "unknown"
      fi

tasks:
  ##################################################################################
  # Meta & Utility Tasks

  default:
    desc: "Run all tasks to set up and configure a Kubernetes cluster."
    cmds:
    - task: deploy

  printenv:
    desc: "Print environment variables."
    cmds:
    - /usr/bin/echo "{{.kube_dir}}"

  init:
    desc: "Initialize directories and configuration files."
    cmds:
    - mkdir -p .kube .pulumi .talos
    - touch {{.kube_config_file}} {{.talos_config_file}}
    - chmod 600 {{.kube_config_file}} {{.talos_config_file}}

  deploy:
    desc: "Deploy all resources."
    deps:
    - clean
    cmds:
    - task: kubernetes
    - task: pulumi

  all-pods-ready:
    desc: "Wait for all Kubernetes pods in the cluster to be ready."
    cmds:
    - bash -c 'until [ "$(kubectl get pods --all-namespaces --no-headers | grep -v "Running\\|Completed\\|Succeeded" | wc -l)" -eq 0 ]; do echo "Waiting for pods..."; sleep 5; done'
    - kubectl get pods --all-namespaces --show-labels --kubeconfig {{.kube_config_file}}

  destroy:
    desc: "Clean up and destroy all Pulumi and Kubernetes resources."
    cmds:
    - task: pulumi-destroy

  act:
    desc: "Test GitHub Actions locally using 'act'."
    cmds:
    - act --container-options "--privileged" --rm --var GITHUB_TOKEN=${GITHUB_TOKEN} --var PULUMI_ACCESS_TOKEN=${PULUMI_ACCESS_TOKEN}

  # TODO: @RUNME resolve issue that requires symlinking dotfiles to root filesystem due to missing env
  clean:
    desc: "Clean up all local Kargo resources."
    cmds:
    - task: pulumi-cancel
    - task: kubernetes-clean
    - task: pulumi-clean
    - ssh-keygen -f "/home/vscode/.ssh/known_hosts" -R "[127.0.0.1]:30590" 2>/dev/null || true
    - rm -rf .talos/manifest/* .kube/config .ssh/known_hosts 2>/dev/null || true
    - rm ${HOME}/.pulumi ${HOME}/.kube ${HOME}/.talos 2>/dev/null || true

  stop:
    desc: "Stop the GitHub Codespace."
    cmds:
    - task: clean
    - gh codespace --codespace ${CODESPACE_NAME} stop

  ##################################################################################
  # Demo VM Tasks

  vm-deploy:
    desc: "Enable the built in pulumi Ubuntu vm iac feature"
    cmds:
    - pulumi config set --path vm.enabled true
    - pulumi up --yes --skip-preview --refresh --stack {{.pulumi_stack_identifier}}

  vm-destroy:
    desc: "Enable the built in pulumi Ubuntu vm iac feature"
    cmds:
    - pulumi config set --path vm.enabled false
    - pulumi up --yes --skip-preview --refresh --stack {{.pulumi_stack_identifier}}

  ##################################################################################
  # Pulumi Tasks

  pulumi-login:
    desc: "Authenticate with Pulumi."
    cmds:
    - task: init
    - pulumi login
    - pulumi install

  pulumi-configure:
    desc: "Configure Pulumi stack settings."
    cmds:
    - pulumi stack select --create {{.pulumi_stack_identifier}} || true
    - pulumi config set --path kubernetes.distribution talos
    - pulumi config set --path kubernetes.context admin@{{.cluster_name}}
    - pulumi config set --path kubernetes.kubeconfig {{.kube_config_file}}
    - pulumi config set --path cilium.enabled false
    - pulumi config set --path multus.enabled false
    - pulumi config set --path vm.enabled false

  pulumi-deploy:
    desc: "Deploy Pulumi infrastructure."
    cmds:
    - task: pulumi-cancel
    - |
      pulumi up --yes --skip-preview --refresh --continue-on-error --stack {{.pulumi_stack_identifier}} || true
      pulumi up --yes --skip-preview --refresh --stack {{.pulumi_stack_identifier}}
    - task: all-pods-ready

  pulumi-destroy:
    desc: "Destroy Pulumi infrastructure."
    cmds:
    - task: pulumi-cancel
    - |
      pulumi down --yes --skip-preview --refresh --stack {{.pulumi_stack_identifier}} || true
      pulumi down --yes --skip-preview --refresh --stack {{.pulumi_stack_identifier}}

  pulumi-cancel:
    desc: "Cancel the Pulumi update."
    cmds:
    - pulumi cancel --yes --stack {{.pulumi_stack_identifier}} 2>/dev/null || true

  pulumi-clean:
    desc: "Clean up all Pulumi resources."
    cmds:
    - task: pulumi-cancel
    - pulumi down --yes --skip-preview --refresh --stack {{.pulumi_stack_identifier}} 2>/dev/null || true

  pulumi:
    desc: "Pulumi Up - Deploy Kargo Kubevirt PaaS IaC"
    cmds:
    - task: pulumi-login
    - task: pulumi-configure
    - task: pulumi-deploy

  ##################################################################################
  # Talos Tasks

  kubernetes-gen-config:
    desc: "Generate Talos cluster configuration."
    cmds:
    - talosctl gen config {{.project}} https://10.0.5.2:6443 --config-patch @{{.talos_patch}} --force --output .talos/manifest --context {{.cluster_name}}

  # TODO: @RUNME resolve issue that requires hardcoding HOME env due to missing env
  kubernetes-deploy:
    desc: "Deploy Kubernetes cluster."
    cmds:
    - task: init
    - |
      talosctl cluster create \
        --arch={{.arch}} \
        --provisioner docker \
        --init-node-as-endpoint \
        --config-patch @{{.talos_patch}} \
        --controlplanes 1 \
        --memory {{.memory}} \
        --exposed-ports {{.exposed_ports}} \
        --context {{.cluster_name}} \
        --name {{.cluster_name}} \
        --workers 0 --crashdump

  kubernetes-ready:
    desc: "Wait for the Talos cluster control plane components to be ready."
    cmds:
    - bash -c 'until kubectl --kubeconfig {{.kube_config_file}} wait --for=condition=Ready pod -l k8s-app=kube-scheduler --namespace=kube-system --timeout=180s; do echo "Waiting for kube-scheduler..."; sleep 5; done' || true
    - bash -c 'until kubectl --kubeconfig {{.kube_config_file}} wait --for=condition=Ready pod -l k8s-app=kube-controller-manager --namespace=kube-system --timeout=180s; do echo "Waiting for kube-controller-manager..."; sleep 5; done' || true
    - bash -c 'until kubectl --kubeconfig {{.kube_config_file}} wait --for=condition=Ready pod -l k8s-app=kube-apiserver --namespace=kube-system --timeout=180s; do echo "Waiting for kube-apiserver..."; sleep 5; done' || true

  kubernetes-clean:
    desc: "Clean up all Kubernetes resources."
    cmds:
    - talosctl cluster destroy --name {{.cluster_name}} 2>/dev/null || true
    - docker rm --force {{.cluster_name}}-controlplane-1 2>/dev/null || true

  kubernetes:
    desc: "Complete setup and configuration of a Kubernetes cluster."
    deps:
    - clean
    cmds:
    - task: init
    - task: kubernetes-gen-config
    - task: kubernetes-deploy
    - task: kubernetes-ready
    - task: all-pods-ready
