apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
metadata:
  name: talos
spec:
  replicas: 0
  selector:
    matchLabels:
      kubevirt.io/vmpool: talos
  virtualMachineTemplate:
    metadata:
      labels:
        kubevirt.io/vmpool: talos
    spec:
      running: true
      template:
        metadata:
          labels:
            kubevirt.io/vmpool: talos
        spec:
          networks:
            - name: eth0
              multus:
                networkName: br0
          domain:
            cpu:
              cores: 1
            resources:
              requests:
                memory: 2Gi
            devices:
              interfaces:
                - name: eth0
                  bridge: {}
              disks:
                - name: talos-root-disk
                  bootOrder: 1
                  disk:
                    bus: virtio
                - name: talos-empty-disk
                  disk:
                    bus: virtio
          volumes:
            - name: talos-root-disk
              dataVolume:
                name: talos-root-dv
            - name: talos-empty-disk
              dataVolume:
                name: talos-empty-dv
      #     - name: talos-root-disk
      #       containerDisk:
      #         image: docker.io/containercraft/talos:latest
      #         imagePullPolicy: Always
      dataVolumeTemplates:
        - metadata:
            name: talos-root-dv
          spec:
            storage:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 32Gi
            source:
              registry:
                url: "docker://docker.io/containercraft/talos:1.7.6"
        - metadata:
            name: talos-empty-dv
          spec:
            storage:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 4Gi
            source:
              blank: {}
