---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu-br0-persistent-volume-vda-root
  namespace: default
spec:
  source:
    registry:
      url: "docker://docker.io/containercraft/ubuntu:22.04"
  pvc:
    storageClassName: "ssd"
    volumeMode: Filesystem
    resources:
      requests:
        storage: 64G
    accessModes:
      - ReadWriteOnce
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-br0-persistent
  namespace: default
  labels:
    app: ubuntu
    feature: xrdp
spec:
  running: true
  template:
    spec:
      domain:
        clock:
          utc: {}
          timer:
            hpet:
              present: False
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
        cpu:
          cores: 1
          sockets: 1
          threads: 6
          model: host-passthrough
          dedicatedCpuPlacement: false
        memory:
          guest: 8G
        machine:
          type: q35
        resources:
          requests:
            memory: 8G
        devices:
          rng: {}
          autoattachPodInterface: false
          autoattachSerialConsole: true
          autoattachGraphicsDevice: true
          networkInterfaceMultiqueue: false
          disks:
            - name: ubuntu-br0-persistent-disk-vda-root
              bootOrder: 1
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: enp1s0
              bridge: {}
        features:
          acpi:
            enabled: true
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: true
      hostname: ccio
      networks:
        - name: enp1s0
          multus:
            networkName: br0
      terminationGracePeriodSeconds: 0
      accessCredentials:
        - sshPublicKey:
            source:
              secret:
                secretName: kc2-pubkey
            propagationMethod:
              qemuGuestAgent:
                users:
                  - "kc2"
      volumes:
        - name: ubuntu-br0-persistent-disk-vda-root
          dataVolume:
            name: ubuntu-br0-persistent-volume-vda-root
        - name: cloudinitdisk
          cloudInitNoCloud:
            networkData: |
              version: 2
              ethernets:
                enp1s0:
                  link-local: []
                  dhcp4: true
                  dhcp6: false
                  dhcp-identifier: mac
                enp2s0:
                  link-local: []
                  dhcp4: true
                  dhcp6: false
                  dhcp-identifier: mac
            userData: |
              #cloud-config
              ssh_pwauth: true
              disable_root: true
              chpasswd:
                list: |
                   kc2:kc2
                expire: False
              users:
                - name: kc2
                  shell: /bin/bash
                  lock_passwd: false
                  sudo: ['ALL=(ALL) NOPASSWD:ALL']
                  groups: sudo,kvm,lxd,libvirt,microk8s,xrdp,docker,ssl-cert
              growpart:
                mode: auto
                devices: ['/']
                ignore_growroot_disabled: true
              package_update: true
              package_upgrade: true
              package_reboot_if_required: true
              packages:
                - vim
                - docker.io
                - neofetch
                - ubuntu-desktop
                - gnome-tweaks
                - firefox
                - xrdp
              reboot: true
              runcmd:
                - screenfetch
                - "apt-get remove apport apport-gtk python3-apport python3-problem-report shim-signed apport-symptoms python3-systemd ansible -y --allow-remove-essential"
                - "apt-get autoremove -y"
                - "snap install helm --classic"
                - "snap install kubectl --classic"
                - "mkdir -p /home/kc2/.kube"
                - "chown -R kc2:kc2 /home/kc2/.kube"
                - "echo H4sIAAAAAAACA7WRwU7DMAyG73mKaHe6dRrTyKsghELibWYhjhy3gBDvTkIXtRJC4oJP8R/ntz/HUTziyeiPTxVBXokv2agb7SZZ6RKYxl0XrRi9Eh5gNYvWe4acje7vtl2/P3S3h65fb3f6X6L13c99I0UosofsGJMgxTJkHTDaFzA6vPkn3pRU3hNcbxLTM7gC4+FohyAqC7E9wWMiCkv2upLfrdvrUsE4AhcFWRXzIwb4i42HEV2trFQg5810av5VacL0LwucGhNSRPedM5E0g2TlbPS6ZQVrOe781mO+/OC5rqfs9v5BuTBkqWxxCEF9AXZkJoMrAgAA | base64 -d | gzip -d | lxd init --preseed"
                - "screenfetch"
                - "ip a"
