# k create secret generic kc2-pubkey --from-file=key1=$HOME/.ssh/id_rsa.pub --dry-run=client -oyaml | k apply -f -
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-ephemeral-nat-ssh
spec:
  type: NodePort
  ports:
    - nodePort: 30590
      port: 30590
      protocol: TCP
      targetPort: 22
  selector:
    kc2.ccio.io/instance: ubuntu-ephemeral-nat
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-ephemeral-nat
  namespace: default
  labels:
    app: kc2
spec:
  running: true
  template:
    metadata:
      labels:
        app: kc2
        kc2.ccio.io/instance: ubuntu-ephemeral-nat
    spec:
      hostname: ubuntu-ephemeral-nat
      domain:
        clock:
          utc: {}
          timer: {}
        cpu:
          cores: 1
          sockets: 1
          threads: 2
          model: host-passthrough
          dedicatedCpuPlacement: false
        memory:
          guest: 4096M
        resources:
          limits:
            memory: 4096M
          requests:
            memory: 4096M
        devices:
          rng: {}
          autoattachPodInterface: false
          autoattachSerialConsole: true
          autoattachGraphicsDevice: true
          networkInterfaceMultiqueue: false
          disks:
            - name: containerdisk
              bootOrder: 1
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: enp1s0
              model: virtio
              bridge: {}
        #features:
        #  acpi:
        #    enabled: true
        #  smm:
        #    enabled: true
        #firmware:
        #  bootloader:
        #    efi:
        #      secureBoot: false
        machine:
          type: q35
      networks:
        - name: enp1s0
          pod: {}
      terminationGracePeriodSeconds: 0
      accessCredentials:
        - sshPublicKey:
            source:
              secret:
                secretName: kc2-pubkey
            propagationMethod:
              qemuGuestAgent:
                users:
                  - "kc2"
      volumes:
        - name: containerdisk
          containerDisk:
            image: docker.io/containercraft/ubuntu:22.04
            imagePullPolicy: Always
        - name: cloudinitdisk
          cloudInitNoCloud:
            networkData: |
              version: 2
              ethernets:
                enp1s0:
                  dhcp4: true
                  dhcp6: false
                  dhcp-identifier: mac
            userData: |
              #cloud-config
              ssh_pwauth: true
              disable_root: true
              chpasswd:
                list: |
                   kc2:kc2
                expire: False
              users:
                - name: kc2
                  shell: /bin/bash
                  lock_passwd: false
                  sudo: ['ALL=(ALL) NOPASSWD:ALL']
                  groups: sudo,lxd,libvirt,microk8s,xrdp,docker,ssl-cert
              growpart:
                mode: auto
                devices: ['/']
                ignore_growroot_disabled: true
              package_upgrade: true
              packages:
                - docker.io
                - neofetch
              runcmd:
                - "echo H4sIAAAAAAACA7WRwU7DMAyG73mKaHe6dRrTyKsghELibWYhjhy3gBDvTkIXtRJC4oJP8R/ntz/HUTziyeiPTxVBXokv2agb7SZZ6RKYxl0XrRi9Eh5gNYvWe4acje7vtl2/P3S3h65fb3f6X6L13c99I0UosofsGJMgxTJkHTDaFzA6vPkn3pRU3hNcbxLTM7gC4+FohyAqC7E9wWMiCkv2upLfrdvrUsE4AhcFWRXzIwb4i42HEV2trFQg5810av5VacL0LwucGhNSRPedM5E0g2TlbPS6ZQVrOe781mO+/OC5rqfs9v5BuTBkqWxxCEF9AXZkJoMrAgAA | base64 -d | gzip -d | lxd init --preseed"
                - "neofetch"
