---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ssd
  volumeMode: Filesystem
  volumeName: nginx-pv
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  annotations:
    kubernetes.io/psp: restricted
    seccomp.security.alpha.kubernetes.io/pod: 'runtime/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName: 'runtime/default'
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
      requests:
        cpu: "0.1"
        memory: "128Mi"
    volumeMounts:
    - name: nginx-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-volume
    persistentVolumeClaim:
      claimName: nginx-pvc
