---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: lan
  namespace: default
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "br0",
      "isGateway": true,
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.1.0/24",
        "rangeStart": "192.168.1.250",
        "rangeEnd": "192.168.1.253",
        "routes": [
          {
            "dst": "0.0.0.0/0"
          }
        ],
        "gateway": "192.168.1.1"
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: k
  annotations:
    k8s.v1.cni.cncf.io/networks: lan
spec:
  containers:
  - name: k
    image: ghcr.io/containercraft/konductor
    resources:
      requests:
        memory: "512Mi"
        cpu: "4000m"
      limits:
        memory: "512Mi"
        cpu: "4000m"
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - "1.1.1.1"
    searches:
      - "example.com"
