# This Github Workflow will run on every push to the repository
# and will test and validate the Kargo codebase using Kind Kubernetes.
name: CI Testing - Konductor on Talos

on: push

jobs:
  readme:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/containercraft/konductor:latest
      options: --user vscode --security-opt seccomp=unconfined

    steps:

      - id: checkout
        name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: list
        name: List Runme Commands
        run: |
          runme -l

      - id: login
        name: Login to Cloud Accounts
        run: |
          runme run login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: configure
        name: Configure Kargo Deployment
        run: |
          runme run configure

      - id: kubernetes
        name: Deploy Kubernetes
        run: |
          runme run kubernetes

      - id: deploy
        name: Deploy Kargo Platform on Kubernetes
        run: |
          runme run deploy
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: clean
        name: Clean Up Kubernetes & Kargo Deployment
        if: always()
        run: |
          runme run clean
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
