# This Github Workflow will run on every push to the repository
# and will test and validate the Kargo codebase using Kind Kubernetes.
name: CI Testing - Konductor on Talos

on: push

jobs:
  ci-kargo-talos:
    runs-on: ubuntu-latest
    env:
      FOO: bar
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    container:
      image: ghcr.io/containercraft/konductor:latest
      options: --user runner --security-opt seccomp=unconfined

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Start Talos K8s Cluster
        run: |
          export PULUMI_ACCESS_TOKEN=${PULUMI_ACCESS_TOKEN} ; make login talos


      - name: Run Pulumi Up
        run: |
          export PULUMI_ACCESS_TOKEN=${PULUMI_ACCESS_TOKEN} ; make up

      - name: Cleanup
        if: always()
        run: |
          export PULUMI_ACCESS_TOKEN=${PULUMI_ACCESS_TOKEN} ; make clean-all
