# This Github Workflow will run on every push to the repository
# and will test and validate the Kargo codebase using Kind Kubernetes.
name: CI Testing - Konductor on Talos

on: push

jobs:
  ci-kargo-talos:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/containercraft/konductor:latest
      options: --user runner --security-opt seccomp=unconfined

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: help
        run: |
          set -ex; make help

      - id: login
        run: |
          set -ex; export PULUMI_ACCESS_TOKEN=${{ env.PULUMI_ACCESS_TOKEN }} ; make login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: talos-config
        run: |
          set -ex; make talos-config

      - id: talos-cluster
        run: |
          set -ex; make talos-cluster

      - id: talos-ready
        run: |
          set -ex; make talos-ready

      - id: pulumi-up
        run: |
          set -ex; export PULUMI_ACCESS_TOKEN=${{ env.PULUMI_ACCESS_TOKEN }} ; make pulumi-up
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: all-pods-ready
        run: |
          set -ex; make all-pods-ready

      - id: pulumi-down
        run: |
          set -ex; export PULUMI_ACCESS_TOKEN=${{ env.PULUMI_ACCESS_TOKEN }} ; make pulumi-down
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: clean
        run: |
          set -ex; make clean

      - name: clean-all
        if: always()
        run: |
          set -ex; export PULUMI_ACCESS_TOKEN=${{ env.PULUMI_ACCESS_TOKEN }} ; make clean-all
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
